version: '3'
services:
  postgres:
    image: sameersbn/postgresql:9.6-2
    ports:
      - 5432:5432
    environment:
      - DB_USER=postgres
      - DB_PASS=postgres
      - PG_PASSWORD=postgres
      - DB_NAME=customer,catalog,bifrost

  jeager:
    image: jaegertracing/all-in-one
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411