version: '3'
services:
  postgres:
    image: sameersbn/postgresql:9.6-2
    ports:
      - 5432:5432
    environment:
      - DB_USER=postgres
      - DB_PASS=postgres
      - PG_PASSWORD=postgres
      - DB_NAME=customer,catalog,bifrost

  jeager:
    image: jaegertracing/all-in-one